on:
  push:
    branches:
      - master
name: Deploy branch to Chalice
jobs:
  deploy:
    name: deploy
    env:
      TDA_API_KEY: ${{ secrets.TDA_API_KEY }}
      PASSPHRASE: ${{ secrets.PASSPHRASE }}
      TDA_TOKEN: ${{ secrets.TDA_TOKEN }}

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: chalice deploy
      uses: jayef0/chalice-extended-action@release-v0.2.1
      env:
        REQUIREMENTS_FILE: requirements.txt
        OPERATION: deploy
        STAGE: dev
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-west-2
